/**
 * LIRR static-schedule query engine ("plan ahead" tools).
 *
 * Reads /data/lirr-schedule.json, a compact index generated by
 * `npm run build:data` from the official LIRR static GTFS:
 *
 *   {
 *     calendar:      { [serviceId]: { days: number[7 (Sun..Sat)], start: "YYYYMMDD", end: "YYYYMMDD" } },
 *     calendarDates: { [serviceId]: { add: ["YYYYMMDD"...], remove: [...] } },
 *     trips:         [ { s: serviceId, st: [ [stopId, arrMin, depMin], ... ] } ]
 *   }
 *
 * Times are minutes since midnight of the *service day* and can exceed 1440
 * (GTFS convention for after-midnight trips). Queries therefore check both the
 * requested date and the previous service day's spillover trips.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

interface CalendarEntry {
  days: number[]; // index 0=Sunday … 6=Saturday, values 0/1
  start: string; // YYYYMMDD
  end: string; // YYYYMMDD
}

interface RawSchedule {
  calendar: Record<string, CalendarEntry>;
  calendarDates: Record<string, { add: string[]; remove: string[] }>;
  trips: { s: string; st: [string, number, number][] }[];
}

let cache: RawSchedule | null = null;

export function loadSchedule(): RawSchedule {
  if (cache) return cache;
  const raw = readFileSync(join(process.cwd(), "data", "lirr-schedule.json"), "utf8");
  cache = JSON.parse(raw) as RawSchedule;
  return cache;
}

export class ScheduleDataMissingError extends Error {
  constructor() {
    super(
      "No LIRR schedule data is bundled with this deployment. Run `npm run build:data` " +
        "locally (it downloads the official MTA static GTFS into /data) and redeploy."
    );
    this.name = "ScheduleDataMissingError";
  }
}

/* --------------------------- date/time helpers --------------------------- */

const NY = "America/New_York";

/** Today's date in New York as YYYY-MM-DD. */
export function todayNy(): string {
  return new Intl.DateTimeFormat("en-CA", { timeZone: NY }).format(new Date());
}

/** Current New York wall-clock time as minutes since midnight. */
export function nowMinutesNy(): number {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: NY,
    hour: "numeric",
    minute: "numeric",
    hour12: false,
  }).formatToParts(new Date());
  const get = (t: string) => Number(parts.find((p) => p.type === t)?.value ?? 0);
  return (get("hour") % 24) * 60 + get("minute");
}

const DATE_RE = /^(\d{4})-(\d{2})-(\d{2})$/;

export function parseDate(date: string): { compact: string; weekday: number } {
  const m = DATE_RE.exec(date);
  if (!m) throw new Error(`Invalid date "${date}" — use YYYY-MM-DD.`);
  const [, y, mo, d] = m;
  const weekday = new Date(Date.UTC(Number(y), Number(mo) - 1, Number(d))).getUTCDay();
  return { compact: `${y}${mo}${d}`, weekday };
}

export function shiftDate(date: string, days: number): string {
  const m = DATE_RE.exec(date);
  if (!m) throw new Error(`Invalid date "${date}"`);
  const dt = new Date(Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]) + days));
  return dt.toISOString().slice(0, 10);
}

export function parseHhMm(t: string): number {
  const m = /^(\d{1,2}):(\d{2})$/.exec(t.trim());
  if (!m) throw new Error(`Invalid time "${t}" — use 24-hour HH:MM, e.g. "18:30".`);
  const h = Number(m[1]);
  const min = Number(m[2]);
  if (h > 23 || min > 59) throw new Error(`Invalid time "${t}".`);
  return h * 60 + min;
}

/** Minutes-since-midnight → "h:mm AM/PM" (handles >24h values). */
export function fmtMin(min: number): string {
  const m = ((min % 1440) + 1440) % 1440;
  const h24 = Math.floor(m / 60);
  const h12 = h24 % 12 === 0 ? 12 : h24 % 12;
  return `${h12}:${String(m % 60).padStart(2, "0")} ${h24 < 12 ? "AM" : "PM"}`;
}

/* ------------------------------ core queries ----------------------------- */

function serviceActive(s: RawSchedule, serviceId: string, compactDate: string, weekday: number): boolean {
  const cd = s.calendarDates[serviceId];
  if (cd?.remove.includes(compactDate)) return false;
  if (cd?.add.includes(compactDate)) return true;
  const c = s.calendar[serviceId];
  if (!c) return false;
  return compactDate >= c.start && compactDate <= c.end && c.days[weekday] === 1;
}

export interface ScheduledTrain {
  /** Departure in minutes relative to midnight of the *queried* date (can be <0 or ≥1440). */
  dep: number;
  arr: number;
  finalStopId: string;
  stops: number; // stops between origin and destination, exclusive
}

function tripsForServiceDay(
  s: RawSchedule,
  originId: string,
  destId: string,
  date: string
): ScheduledTrain[] {
  const { compact, weekday } = parseDate(date);
  const out: ScheduledTrain[] = [];
  for (const trip of s.trips) {
    if (!serviceActive(s, trip.s, compact, weekday)) continue;
    const st = trip.st;
    let oIdx = -1;
    for (let i = 0; i < st.length; i++) {
      if (st[i][0] === originId) {
        oIdx = i;
        break;
      }
    }
    if (oIdx === -1) continue;
    let dIdx = -1;
    for (let i = oIdx + 1; i < st.length; i++) {
      if (st[i][0] === destId) {
        dIdx = i;
        break;
      }
    }
    if (dIdx === -1) continue;
    out.push({
      dep: st[oIdx][2],
      arr: st[dIdx][1],
      finalStopId: st[st.length - 1][0],
      stops: dIdx - oIdx - 1,
    });
  }
  return out;
}

export interface FindTrainsOptions {
  originId: string;
  destId: string;
  date: string; // YYYY-MM-DD
  departAfterMin?: number; // wall-clock minutes on `date`
  arriveByMin?: number; // wall-clock minutes on `date`
  limit: number;
}

/**
 * Scheduled trains for a wall-clock window on `date`, including after-midnight
 * trips that GTFS files under the previous service day.
 */
export function findTrains(opts: FindTrainsOptions): ScheduledTrain[] {
  const s = loadSchedule();
  if (s.trips.length === 0) throw new ScheduleDataMissingError();

  const after = opts.departAfterMin ?? 0;
  const sameDay = tripsForServiceDay(s, opts.originId, opts.destId, opts.date);
  // Previous service day's >24h trips land on `date`'s early morning.
  const spill = tripsForServiceDay(s, opts.originId, opts.destId, shiftDate(opts.date, -1))
    .filter((t) => t.dep >= 1440)
    .map((t) => ({ ...t, dep: t.dep - 1440, arr: t.arr - 1440 }));

  let all = [...spill, ...sameDay].filter((t) => t.dep >= after);
  if (opts.arriveByMin !== undefined) {
    const byMin = opts.arriveByMin;
    // Latest departures that still arrive in time.
    all = all.filter((t) => t.arr <= byMin).sort((a, b) => b.dep - a.dep).slice(0, opts.limit);
  }
  return all.sort((a, b) => a.dep - b.dep).slice(0, opts.limit);
}

/** First and last scheduled departures for the service day. */
export function firstLastTrains(
  originId: string,
  destId: string,
  date: string
): { first: ScheduledTrain; last: ScheduledTrain } | null {
  const s = loadSchedule();
  if (s.trips.length === 0) throw new ScheduleDataMissingError();
  const trains = tripsForServiceDay(s, originId, destId, date).sort((a, b) => a.dep - b.dep);
  if (trains.length === 0) return null;
  return { first: trains[0], last: trains[trains.length - 1] };
}
