/**
 * Static station data + fuzzy name resolution.
 *
 * The JSON files in /data are generated by `npm run build:data`
 * (scripts/build-stations.mjs), which pulls the official MTA static
 * GTFS / stations datasets. They ship empty so nothing here can lie —
 * tools return a clear "run build:data" error until they're populated.
 */
import lirrStopsRaw from "@/data/lirr-stops.json";
import subwayStopsRaw from "@/data/subway-stops.json";

export interface LirrStop {
  id: string;
  name: string;
}

export interface SubwayStop {
  id: string; // GTFS parent stop id, e.g. "R01"; platform ids are `${id}N` / `${id}S`
  name: string;
  routes: string[]; // daytime routes serving the station
  borough?: string;
}

export const lirrStops = lirrStopsRaw as LirrStop[];
export const subwayStops = subwayStopsRaw as SubwayStop[];

export class StationDataMissingError extends Error {
  constructor(system: string) {
    super(
      `No ${system} station data is bundled with this deployment. ` +
        `Run \`npm run build:data\` locally (it downloads the official MTA static datasets ` +
        `into /data) and redeploy.`
    );
    this.name = "StationDataMissingError";
  }
}

/* ------------------------- fuzzy matching ------------------------- */

const ALIASES: Record<string, string> = {
  penn: "penn station",
  nyp: "penn station",
  "new york penn": "penn station",
  gcm: "grand central madison",
  "grand central": "grand central madison",
  gct: "grand central madison",
  atlantic: "atlantic terminal",
  brooklyn: "atlantic terminal",
};

function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/[.\-–—/]/g, " ")
    .replace(/\b(st|street)\b/g, "st")
    .replace(/\b(av|ave|avenue)\b/g, "av")
    .replace(/\b(blvd|boulevard)\b/g, "blvd")
    .replace(/\b(rd|road)\b/g, "rd")
    .replace(/\s+/g, " ")
    .trim();
}

function score(query: string, candidate: string): number {
  if (candidate === query) return 100;
  if (candidate.startsWith(query)) return 85;
  if (candidate.includes(query)) return 70;
  const qTokens = query.split(" ");
  const cTokens = new Set(candidate.split(" "));
  const overlap = qTokens.filter((t) => cTokens.has(t)).length;
  if (overlap === 0) return 0;
  return Math.round((overlap / qTokens.length) * 60);
}

export interface Match<T> {
  station: T;
  score: number;
}

function rank<T extends { name: string }>(query: string, stations: T[]): Match<T>[] {
  const q = normalize(ALIASES[normalize(query)] ?? query);
  return stations
    .map((station) => ({ station, score: score(q, normalize(station.name)) }))
    .filter((m) => m.score > 0)
    .sort((a, b) => b.score - a.score);
}

/**
 * Resolve a user-supplied station name. Returns the best match, or throws
 * with suggestions so the model can self-correct on the next call.
 */
export function resolveStation<T extends { name: string }>(
  query: string,
  stations: T[],
  system: "LIRR" | "subway"
): T {
  if (stations.length === 0) throw new StationDataMissingError(system);
  const matches = rank(query, stations);
  if (matches.length === 0) {
    throw new Error(`No ${system} station matched "${query}". Try the full station name.`);
  }
  const [best, second] = matches;
  // Ambiguous: two similar-strength partial matches — ask instead of guessing.
  if (best.score < 85 && second && second.score >= best.score - 10) {
    const options = matches.slice(0, 5).map((m) => m.station.name).join("; ");
    throw new Error(
      `"${query}" is ambiguous for ${system}. Closest matches: ${options}. ` +
        `Call again with one of these exact names.`
    );
  }
  return best.station;
}
